apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: microbot
 namespace: microbot
 annotations:
  cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - hosts:
    - microbot.ubuntuix.local
    secretName: microbot-ingress-tls
  rules:
  - host: microbot.ubuntuix.local
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: microbot
           port:
             number: 80

